-- Add onboarding fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS year VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS major VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS isOnboarded BOOLEAN DEFAULT FALSE; 